sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack --no-terminal setup
- git clone https://github.com/mizunashi-mana/hpc-coveralls.git ~/.local/src/hpc-coveralls
- git -C ~/.local/src/hpc-coveralls fetch
- git -C ~/.local/src/hpc-coveralls checkout -b add-stack-support origin/add-stack-support
- sh -c 'cd ~/.local/src/hpc-coveralls && stack --no-terminal init . && stack --no-terminal install'

install:
# Build dependencies
- stack --no-terminal build --only-dependencies --coverage

script:
# Build the package, its tests, and its docs and run the tests
- stack --no-terminal test --haddock --no-haddock-deps --coverage

after_script:
- hpc-coveralls spec-test --exclude-dir=test --display-report --repo-token $COVERALLS_REPO_TOKEN

env:
  global:
    secure: dopxG+mcs3e8lQGYFxTxi2OpBmWeVDxVF7Rrh/AS6cIcYMno4Lj62UGmjS8cQ/RJBIv1jc6ifXWDDu5ieyujf55MCoiy3dS21WSWWa2wZ5hfxP1TTIHLwkfKEtV1yJZ5ZTIPy1QTq18NQ0ZEjfg0Q9VnwJFNZ83+bUEmtaibvDa6Yi+M16l8Mng91SF2x40Y98EEJXD3/qc+8ou6gNPFJ9oRyCFhS5wQiGcS3gwqZ6iw9/R5BbNbBGbNA6T6aL6o5+kXBW/x1f1MtZsi5G9suX+jVFvM6RIy2klMbque1d4bsdbjoMV8ywCMJhZiPA8gArAR/4MWvHiLaIhqEEbtzqm9LqcR2h4kx4ghSl4LcMJTh+RaWPnVqEqwt6yOaLjwZG/zXlkKTwdClbOj8qGihcSSswVMdSKblxUCq8BQlw94QEwjdeukbeIs9mwzM8A3Jx564jdd6jp4nYYRFR23MYFND6o3qmwA3aHY0vtQKMwaWxY99qREFfxEUdcZ3KUriumRViKUncDzgAjQB4lhViJrPjpD+NUzugD/PW8FVeyPMrM2vST6gawXkEDrnGTMemanvT14aSYc1zqrKCC2Ikx3pZZjMQTtX5gHVJmEY2sK4Ets7+UWa4pKeIboP2P1+QskXjDMg4ddWzRQ9a4KE9wldaPR5vFqos8YF0/7/nQ=
